// pages/more-rewards.tsx
import React from "react";
import vbg from "../../../../../public/images/vbg.png";
import iconA from "../../../../../public/icons/partnerB.png";

const CardBenefit: React.FC = () => {
  /* const rewards = [
    "Share 30% of profit generated by Manilla Finance. This reward is distributed in USDT, USDC, or DAI",
    "Earn 10% MNLA on your staked tokens",
    "Get freebies year round – from data bundles, utility bills, event tickets and many more",
    "Huge discount on flight & hotel bookings within the Manilla app",
  ]; */

  return (
    <main className="bg-gray-50  p-6 sm:p-12 border-t-2 border-black/20 border-dashed">
      <div className="flex items-center justify-bewteen  mb-6 md:mb-10">
        <div className="flex-1 ">
          <div className="hidden md:inline-flex items-center bg-gray-100/70  gap-2 text-xs font-medium px-6 py-2 rounded-full border border-gray-200 hover:shadow-md transition">
            Loyalty Reward
          </div>
        </div>
        <div className="mx-auto flex flex-1 justify-center -translate-y-9">
          <div className="inline-flex items-center gap-3 -translate-y-9 ">
            <h2
              className=" scale-90 py-8 px-20 "
              style={{
                backgroundImage: `url(${vbg.src})`,
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                backgroundSize: "contain", // optional, makes sure it fills the area
              }}
            >
              <span className="font-semibold text-nowrap text-sm ">
                Loyalty Reward
              </span>
            </h2>
          </div>
        </div>

        <div className="text-right flex-1">
          {/* keep spacing on right for desktop */}
          <div className="hidden sm:block"></div>
        </div>
      </div>

      <div className="flex justify-center -translate-y-8">
        <p className="px-6 text-lg md:text-xl font-semibold  py-2 text-black -translate-y-9">
          Benefits of Manilla Card
        </p>
      </div>
      <div className="flex justify-center -translate-y-15">
        <p className="px-6 text-xs py-2 text-black   text-center">
          Here are the benefits you can get just for owing a Manilla card
        </p>
      </div>
      <div className="md:max-w-5xl mx-auto flex flex-col md:flex-row items-start gap-10 ">
        {/* Right side - Illustration */}
        <section
          className="flex-1 bg-blue-800 relative bg-cover bg-center text-white py-8  px-6  md:px-8 rounded-4xl overflow-hidden mt-[-15]"
          style={{ backgroundImage: "url('/images/benefitcardPartern.png')" }}
        >
          <div className="max-w-6xl mx-auto  lg:px-6 text-center">
            {/* Button */}
            <button className="bg-black text-white px-6 py-1  md:py-3 rounded-full font-semibold text-lg shadow-lg mt-[-]">
              Manilla Card Benefits
            </button>

            {/* Subtitle */}
            <p className="mt-4 mx-auto text-base md:text-5px text-gray-100">
             Manilla Crypto Card unlocks borderless spending power, turning your digital assets into everyday payments worldwide
            </p>

            {/* Card Section */}
            <div className="mt-5 grid grid-cols-1 md:grid-cols-3 gap-2  ">
              {/* Card 1 */}
              <div className="text-white bg-[#3437CC] rounded-2xl shadow-lg  p-2 flex flex-col items-center">
                <img
                  src="/icons/iconyellow.png"
                  alt="Zero Fast"
                  className="w-7 h-7"
                />
                <h2 className=" md:text-base font-semibold mb-3">Easy Spend</h2>
                <p className="text-sm md:text-xs  text-white text-center">
                  With Manilla Card, spend your crypto like cash—converted instantly to fiat at checkout, online or in-store.
                </p>
              </div>

              {/* Card 2 */}
              <div className="text-white bg-[#3437CC] rounded-2xl shadow-lg p-2 flex flex-col items-center">
                <img
                  src="/icons/iconyellow.png"
                  alt="Benefit 2"
                  className="w-7 h-7"
                />
                <h2 className="text-lg md:text-base font-semibold mb-3">
                  Accepted Globally
                </h2>
                <p className="text-sm md:text-xs text-white text-center">
                  Manilla Card is powered by Mastercard, giving you global access anywhere traditional cards are accepted—without limits or borders.
                </p>
              </div>

              {/* Card 3 */}
              <div className="text-white bg-[#3437CC] rounded-2xl shadow-lg p-2 flex flex-col items-center">
                <img
                  src="/icons/iconyellow.png"
                  alt="Benefit 3"
                  className="w-7 h-7"
                />
                <h2 className="text-lg md:text-base font-semibold mb-3">
                  Crypto Rewards
                </h2>
                <p className="text-sm md:text-xs text-white text-center">
                 Earn high crypto cashback with Manilla Card, plus exclusive perks like discounts, travel, and lifestyle benefits.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Left side - Rewards list */}
        <div className="flex-1 flex flex-col gap-5 bg-white w-full">
          <div className="bg-gray-200/70 rounded p-3 text-center md:text-start">
            <h3 className="font-semibold flex items-center gap-2 justify-center">
              Benefits of Manilla Card
            </h3>
            <p className="text-slate-700 font-medium text-xs mt-2 flex justify-center">
              Play it smart, diversify your portfolio from cashback.
            </p>
          </div>

          <div className="bg-gray-200/70 rounded-2xl p-3 text-center md:text-start">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Variety of Choices Available
            </h3>
            <p className="text-xs leading-4 mt-1">
              Unlike traditional debit cards, you won&apos;t find hidden
              charges, annual fees, or maintenance costs.
            </p>
          </div>

          <div className="bg-gray-200/70 rounded-2xl p-3 text-center md:text-start">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Instant Access to Crypto Rewards
            </h3>
            <p className="text-xs leading-4 mt-1">
              Accumulate your crypto rewards over time and access them instantly
              whenever needed.
            </p>
          </div>

          <div className="bg-gray-200/70 rounded-2xl p-3 text-center md:text-start">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Boost Your MNLA Cashback
            </h3>
            <p className="text-xs leading-4 mt-1">
              Stake your MNLA rewards using the Manilla Vault and watch them
              grow.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
};
export default CardBenefit;
