import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminWrapper from "@/components/AdminWrapper";

export const metadata: Metadata = {
  title: "Manilla",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AdminWrapper>
          {children}
        </AdminWrapper>
      </body>
    </html>
  );
}
