// pages/more-rewards.tsx
import React from "react";
import vbg from "../../../../../public/images/vbg.png";
import suit5 from "../../../../../public/images/suit5.png";
import suit4 from "../../../../../public/images/suit4.png";
import icon from "../../../../../public/icons/dropdownIcon.png";
import iconA from "../../../../../public/icons/partnerA.png";
import iconB from "../../../../../public/icons/partnerB.png";
const Rewards: React.FC = () => {
  const rewards = [
    "Share 30% of profit generated by Manilla Finance. This reward is distributed in USDT, USDC, or DAI",
    "Earn 10% MNLA on your staked tokens",
    "Get freebies year round – from data bundles, utility bills, event tickets and many more",
    "Huge discount on flight & hotel bookings within the Manilla app",
  ];

  return (
    <main className="bg-gray-50  p-6 sm:p-12 border-t-2 border-black/20 border-dashed relative">
      <div className="absolute bg-green-300 p-20 lg:p-30 top-10 md:left-15 left-0.5 blur-[100px]"></div>
      <div className="absolute bg-cyan-300 p-20 lg:p-24 bottom-20 lg:bottom-5 right-0.5 md:right-15 blur-[100px]"></div>

      <div className="mx-auto flex flex-1 justify-center -translate-y-9">
        <div className="inline-flex items-center gap-3 -translate-y-9 ">
          <h2
            className="  py-8 px-20 flex  items-center justify-center scale-75 md:scale-90 "
            style={{
              backgroundImage: `url(${vbg.src})`,
              backgroundPosition: "center",
              backgroundRepeat: "no-repeat",
              backgroundSize: "contain", // optional, makes sure it fills the area
            }}
          >
            <span className="font-semibold text-nowrap text-sm ">
              Loyalty Reward
            </span>
            <img src={icon.src} alt="icon" className="w-10" />
          </h2>
        </div>
      </div>
      <div className="flex justify-center">
        <p className="px-6 text-xs py-2 bg-gray-200 rounded-full text-gray-700 font-medium -translate-y-9">
          Learn About Our Loyalty Reward
        </p>
      </div>
      {/* Top */}
      <div className="md:max-w-5xl mx-auto flex flex-col md:flex-row items-center max-w-sm gap-10">
        {/* Right side - Illustration */}
        <div className="flex-1 flex justify-center relative">
          {/* Cloud + Logo */}{" "}
          <img
            src={suit4.src}
            alt="M logo"
            className=" md:flex-1 md:scale-90  w-80 md:w-auto h-auto"
          />
        </div>

        {/* Left side - Rewards list */}
        <div className="flex-1 w-full">
          <div className="bg-gray-100/60 rounded-2xl p-4 shadow-xl text-center md:text-start ">
            <h3 className="font-semibold flex items-center gap-2">
              <img src={iconB.src} alt="icon" className="w-8" /> Benefits of
              MNLA Token
            </h3>
            <p className="text-slate-700  mb-4 leading-5 text-xs mt-2">
              The Manilla ecosystem is built around its community. To unlock the
              full benefits of this powerful platform, start by holding the
              Manilla token. Then, download the Manilla app from Google Play or
              the App Store, depending on your device. After registration and
              KYC approval, stake at least 100,000,000 MNLA in the MNLA Vault to
              qualify for the industry's largest no-tier loyalty reward program.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row md:gap-4 gap-2 text-xs mt-4 p-2 rounded-2xl bg-gray-200/70">
            <div className="flex gap-3 justify-center items-center">
              <p className="flex gap-1 items-center ">
                {" "}
                <img src={iconA.src} alt="icon" className="w-7" />
                Staking Type
              </p>
              <span className="rounded-full px-4 py-1 text-white bg-black">
                Lock
              </span>
            </div>
            <div className="flex gap-3 justify-center items-center">
              <p className="flex gap-0.5 items-center">
                <img src={iconA.src} alt="icon" className="w-7" /> Staking
                Duration
              </p>
              <span className="rounded-full px-4 py-1 text-white bg-black text-nowrap">
                365 Days
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* bottom */}
      <div className="md:max-w-6xl mx-auto flex flex-col md:flex-row items-center max-w-sm gap-10">
        {/* Left side - Rewards list */}
        <div className="flex-7/12 w-full">
          {/* List */}
          <ul className="mt-6 space-y-4">
            {rewards.map((text, i) => (
              <li
                key={i}
                className="flex items-start bg-white p-4 rounded-xl shadow-sm border border-slate-100"
              >
                {/* Custom bullet */}
                <img src={iconA.src} alt="icon" className="w-7" />
                {/* Text */}
                <p className="ml-3 text-slate-700 text-sm">{text}</p>
              </li>
            ))}
          </ul>
        </div>

        {/* Right side - Illustration */}
        <div className="flex-5/12 flex justify-center relative">
          {/* Cloud + Logo */}{" "}
          <img
            src={suit5.src}
            alt="M logo"
            className=" md:flex-1 w-80 md:w-auto h-auto"
          />
          {/* <div className="relative w-64 h-64 md:w-80 md:h-80">
             
            </div> */}
        </div>
      </div>
    </main>
  );
};
export default Rewards;
