// pages/more-rewards.tsx
import React from "react";
import vbg from "../../../../../public/images/vbg.png";
import card from "../../../../../public/images/card2.png";
import iconA from "../../../../../public/icons/partnerB.png";

const CardBenefit: React.FC = () => {
  /* const rewards = [
    "Share 30% of profit generated by Manilla Finance. This reward is distributed in USDT, USDC, or DAI",
    "Earn 10% MNLA on your staked tokens",
    "Get freebies year round – from data bundles, utility bills, event tickets and many more",
    "Huge discount on flight & hotel bookings within the Manilla app",
  ]; */

  return (
    <main className="bg-gray-50  p-6 sm:p-12 border-t-2 border-black/20 border-dashed">
      <div className="flex items-center justify-bewteen  mb-6 md:mb-10">
        <div className="flex-1 ">
          <div className="hidden md:inline-flex items-center bg-gray-100/70  gap-2 text-xs font-medium px-6 py-2 rounded-full border border-gray-200 hover:shadow-md transition">
            Loyalty Reward
          </div>
        </div>
        <div className="mx-auto flex flex-1 justify-center -translate-y-9">
          <div className="inline-flex items-center gap-3 -translate-y-9 ">
            <h2
              className=" scale-90 py-8 px-20 "
              style={{
                backgroundImage: `url(${vbg.src})`,
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                backgroundSize: "contain", // optional, makes sure it fills the area
              }}
            >
              <span className="font-semibold text-nowrap text-sm ">
                Loyalty Reward
              </span>
            </h2>
          </div>
        </div>

        <div className="text-right flex-1">
          {/* keep spacing on right for desktop */}
          <div className="hidden sm:block"></div>
        </div>
      </div>

      <div className="flex justify-center -translate-y-8">
        <p className="px-6 text-lg md:text-xl font-semibold  py-2 text-black -translate-y-9">
          Benefits of Manilla Card
        </p>
      </div>
      <div className="flex justify-center -translate-y-15">
        <p className="px-6 text-xs py-2 text-black   text-center">
          Here are the benefits you can get just for owing a Manilla card
        </p>
      </div>
      {/* Top */}
      <div className="md:max-w-5xl mx-auto flex flex-col md:flex-row items-center max-w-sm gap-10">
        {/* Right side - Illustration */}
        <div className="flex-1 flex justify-center relative">
          {/* Cloud + Logo */}{" "}
          <img
            src={card.src}
            alt="M logo"
            className=" md:flex-1   w-80 md:w-auto h-auto"
          />
        </div>

        {/* Left side - Rewards list */}
        <div className="flex-1 flex flex-col gap-2 bg-white w-full">
          <div className="bg-gray-200/70 rounded p-2 text-center  ">
            <h3 className="font-semibold flex items-center gap-2">
              <img src={iconA.src} alt="icon" className="w-7" />
              Benefits of Manilla Card
            </h3>
            <p className="text-slate-700 font-medium   text-xs mt-2">
              Play it smart, diversify your portfolio from cashback.
            </p>
          </div>
          <div className="bg-gray-200/70 rounded p-2  text-center md:text-start ">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Variety of Choices Available
            </h3>
            <p className=" text-xs  leading-4 mt-1">
              Unlike traditional debit cards, you won’t find hidden charges,
              annual fees, or maintenance costs. Just enjoy seamless access to
              everything Manilla offers you today.
            </p>
          </div>
          <div className="bg-gray-200/70 rounded p-2  text-center md:text-start ">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Instant Access to Crypto Rewards
            </h3>
            <p className=" text-xs leading-4mt-1 ">
              Accumulate your crypto rewards over time and access them instantly
              whenever needed. No delays, no restrictions—your assets are always
              ready whenever you want them.
            </p>
          </div>
          <div className="bg-gray-200/70 rounded p-2   text-center md:text-start ">
            <h3 className="font-semibold text-xs flex items-center gap-1">
              <img src={iconA.src} alt="icon" className="w-7" />
              Boost Your MNLA Cashback
            </h3>
            <p className=" text-xs leading-4 mt-1 ">
              Stake your MNLA rewards using the Manilla Vault and watch them
              grow. This is your path to increasing returns and unlocking
              exponential cashback benefits long-term.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
};
export default CardBenefit;
